name: Deploy Vulnerable Application                                  # workflow name

on:
  push:
    branches:
      - master
jobs:
  deploy-heroku:
    name: Deploy Heroku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.add2d829-afb8-4d33-b597-3b0ff6ef8c1f}}
          heroku_app_name: "vulnerable-web-app-flestard" #Must be unique in Heroku
          heroku_email: "flestard@gmail.com"
          remote_branch: "master"
          usedocker: true
